[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "textlib"
version = "0.1.0"
description = "Librería simple de manipulación de texto para laboratorio CI"
requires-python = ">=3.10"

[tool.pytest.ini_options]
pythonpath = ["."]
